using System;

namespace Dibix.Sdk.CodeGeneration
{
    [Flags]
    public enum SchemaDefinitionSource
    {
        Unknown = 0,
        Defined = 1,
        AutoGenerated = 2,
        Local = Defined | AutoGenerated,
        Foreign = 4,
        Internal = 8
    }
}