/*------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------*/
using System.Reflection;
using Dibix;

namespace This.Is.A.Custom.Namespace
{
    internal static class Accessor
    {
        // dbx_tests_sources_includednested
        public const string dbx_tests_sources_includednestedCommandText = @"";

        // dbx_tests_sources_excludednested
        public const string dbx_tests_sources_excludednestedCommandText = @"";

        // dbx_tests_sources_externalsp
        public const string dbx_tests_sources_externalspCommandText = @"[dbo].[dbx_tests_externalsp]";

        public static int dbx_tests_sources_includednested(this IDatabaseAccessorFactory databaseAccessorFactory)
        {
            using (IDatabaseAccessor accessor = databaseAccessorFactory.Create())
            {
                return accessor.Execute(dbx_tests_sources_includednestedCommandText);
            }
        }
        public static int dbx_tests_sources_excludednested(this IDatabaseAccessorFactory databaseAccessorFactory)
        {
            using (IDatabaseAccessor accessor = databaseAccessorFactory.Create())
            {
                return accessor.Execute(dbx_tests_sources_excludednestedCommandText);
            }
        }
        public static int dbx_tests_sources_externalsp(this IDatabaseAccessorFactory databaseAccessorFactory)
        {
            using (IDatabaseAccessor accessor = databaseAccessorFactory.Create())
            {
                return accessor.Execute(dbx_tests_sources_externalspCommandText, System.Data.CommandType.StoredProcedure);
            }
        }

        public static MethodInfo dbx_tests_sources_includednestedMethodInfo { get { return typeof(Accessor).GetMethod("dbx_tests_sources_includednested"); }  } 
        public static MethodInfo dbx_tests_sources_excludednestedMethodInfo { get { return typeof(Accessor).GetMethod("dbx_tests_sources_excludednested"); }  } 
        public static MethodInfo dbx_tests_sources_externalspMethodInfo { get { return typeof(Accessor).GetMethod("dbx_tests_sources_externalsp"); }  } 
    }
}