//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dibix.Generators.Tests
{
    internal static class AnotherResource
    {
        public static string AnotherText => Cache.AnotherText.Value;

        private static class Cache
        {
            public static readonly global::System.Lazy<string> AnotherText = new global::System.Lazy<string>(() => ResourceUtility.GetEmbeddedResourceContent("Dibix.Generators.Tests.Resources.AnotherText.json"));
        }

        private static class ResourceUtility
        {
            private static readonly global::System.Reflection.Assembly ThisAssembly = typeof(ResourceUtility).Assembly;

            public static string GetEmbeddedResourceContent(string resourceKey)
            {
                using (global::System.IO.Stream stream = ThisAssembly.GetManifestResourceStream(resourceKey))
                {
                    if (stream == null)
                        throw new global::System.InvalidOperationException($@"Resource not found: {resourceKey}
    {ThisAssembly.Location}");

                    using (global::System.IO.TextReader reader = new global::System.IO.StreamReader(stream))
                    {
                        string content = reader.ReadToEnd();
                        return content;
                    }
                }
            }
        }
    }
}