//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dibix.Generators.Tests.Tasks
{
    [global::System.CodeDom.Compiler.GeneratedCode("Dibix.Sdk.Generators", "%GENERATORVERSION%")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed class BuildCommandInput
    {
        public global::Dibix.Generators.Tests.Tasks.ArtifactGenerationInput ArtifactGeneration { get; } = new global::Dibix.Generators.Tests.Tasks.ArtifactGenerationInput();
        public global::Dibix.Generators.Tests.Tasks.BuildInput Build { get; } = new global::Dibix.Generators.Tests.Tasks.BuildInput();
        public global::Dibix.Generators.Tests.Tasks.SqlCodeAnalysisInput SqlCodeAnalysis { get; } = new global::Dibix.Generators.Tests.Tasks.SqlCodeAnalysisInput();
    }
}