//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
using System;

namespace Dibix.Sdk
{
    [global::System.CodeDom.Compiler.GeneratedCode("Dibix.Sdk.Generators", "%GENERATORVERSION%")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::Microsoft.CodeAnalysis.Embedded]
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = true)]
    public sealed class CommandLineInputPropertyAttribute : Attribute
    {
        public string Name { get; }
        public CommandLineInputPropertyType Type { get; }
        public string? Category { get; set; }

        public CommandLineInputPropertyAttribute(string name, CommandLineInputPropertyType type)
        {
            Name = name;
            Type = type;
        }
    }
}
#nullable restore