//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dibix.Sdk
{
    [global::System.CodeDom.Compiler.GeneratedCode("Dibix.Sdk.Generators", "%GENERATORVERSION%")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::Microsoft.CodeAnalysis.Embedded]
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true)]
    internal sealed class CommandLineActionArgumentAttribute : global::System.Attribute
    {
        public string Name { get; }
        public global::System.Type Type { get; }
        public string Description { get; }

        public CommandLineActionArgumentAttribute(string name, global::System.Type type, string description)
        {
            Name = name;
            Type = type;
            Description = description;
        }
    }
}