//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dibix.Generators.Tests.Tasks
{
    [global::System.CodeDom.Compiler.GeneratedCode("Dibix.Sdk.Generators", "%GENERATORVERSION%")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public partial class DibixRootCommand : global::System.CommandLine.RootCommand
    {
        public DibixRootCommand(global::Dibix.Sdk.Abstractions.ILogger logger, string description = "") : base(description)
        {
            Add(new global::Dibix.Generators.Tests.Tasks.DumpLockFileCommand(logger));
            Add(new global::Dibix.Generators.Tests.Tasks.BuildCommand(logger));
            Add(new global::Dibix.Generators.Tests.Tasks.SignDacFileCommand(logger));
        }
    }
}