//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dibix.Generators.Tests.Tasks
{
    [global::System.CodeDom.Compiler.GeneratedCode("Dibix.Sdk.Generators", "%GENERATORVERSION%")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public partial class DumpLockFileCommand : global::System.CommandLine.Command
    {
        private readonly global::Dibix.Sdk.Abstractions.ILogger _logger;
        private readonly global::System.CommandLine.Argument<string> _lockFilePathArgument;
        private readonly global::System.CommandLine.Argument<string> _dumpFilePathArgument;

        public DumpLockFileCommand(global::Dibix.Sdk.Abstractions.ILogger logger) : base("dumplockfile", "Reads the given binary lock file and writes it to a human readable json file.")
        {
            _logger = logger;
            _lockFilePathArgument = new global::System.CommandLine.Argument<string>("lockFilePath") { Description = "Path to the binary lock file." };
            _dumpFilePathArgument = new global::System.CommandLine.Argument<string>("dumpFilePath") { Description = "Path to the target JSON file." };

            Add(_lockFilePathArgument);
            Add(_dumpFilePathArgument);

            SetAction(OnExecuteAction);
        }

        public partial global::System.Threading.Tasks.Task<int> Execute(string lockFilePath, string dumpFilePath);

        private async global::System.Threading.Tasks.Task<int> OnExecuteAction(global::System.CommandLine.ParseResult result, global::System.Threading.CancellationToken cancellationToken)
        {
            string lockFilePath = result.GetValue(_lockFilePathArgument);
            string dumpFilePath = result.GetValue(_dumpFilePathArgument);
            int exitCode = await Execute(lockFilePath, dumpFilePath).ConfigureAwait(false);
            return exitCode;
        }
    }
}