//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dibix.Generators.Tests.Tasks2
{
    public sealed partial class EndpointTests2
    {
        internal static partial void EndpointTests2_Endpoint1_Endpoint(global::Dibix.IDatabaseAccessorFactory databaseAccessorFactory);
        internal static partial void EndpointTests2_Endpoint2_Endpoint(global::Dibix.IDatabaseAccessorFactory databaseAccessorFactory);
        internal static partial void EndpointTests2_Endpoint2_Authorization(global::Dibix.IDatabaseAccessorFactory databaseAccessorFactory);
    }
}