//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable RedundantNameQualifier
// ReSharper disable UnusedMember.Global
namespace Dibix.Testing.Generators
{
    [global::System.CodeDom.Compiler.GeneratedCode("Dibix.Testing.Generators", "%GENERATORVERSION%")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::System.AttributeUsage(global::System.AttributeTargets.Method)]
    internal sealed class EndpointAttribute : global::System.Attribute
    {
        public bool WithAuthorization { get; set; }
        public bool Anonymous { get; set; }
#pragma warning disable CS8618
        public string ActionName { get; set; }
#pragma warning restore CS8618
    }
}