//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dibix.Generators.Tests.Tasks1
{
    [global::System.CodeDom.Compiler.GeneratedCode("Dibix.Testing.Generators", "%GENERATORVERSION%")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed partial class EndpointTests1
    {
        internal static partial void EndpointTests1_Endpoint1_Endpoint(global::Dibix.IDatabaseAccessorFactory databaseAccessorFactory);
        internal static partial void EndpointTests1_Endpoint2_Endpoint(global::Dibix.IDatabaseAccessorFactory databaseAccessorFactory);
    }
}