//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dibix.Generators.Tests.Tasks
{
    [global::System.CodeDom.Compiler.GeneratedCode("Dibix.Generators", "1.2.32.48572")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed class EndpointConfiguration
    {
        public bool EnableExperimentalFeatures { get; set; }
        public string BaseUrl { get; set; } = "http://localhost";
    }
}