//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dibix.Generators.Tests
{
    internal static partial class HttpClientExtensions
    {
        public static global::System.Threading.Tasks.Task<global::System.Net.Http.HttpResponseMessage> EndpointTests1_EndpointTests1_Endpoint1_Endpoint(this global::System.Net.Http.HttpClient httpClient)
        {
            return httpClient.GetAsync("api/Tests/EndpointTests1");
        }
        public static global::System.Threading.Tasks.Task<global::System.Net.Http.HttpResponseMessage> EndpointTests1_EndpointTests1_Endpoint2_Endpoint(this global::System.Net.Http.HttpClient httpClient)
        {
            return httpClient.GetAsync("api/Tests/EndpointTests1/Endpoint2");
        }
        public static global::System.Threading.Tasks.Task<global::System.Net.Http.HttpResponseMessage> EndpointTests2_EndpointTests2_Endpoint1_Endpoint(this global::System.Net.Http.HttpClient httpClient)
        {
            return httpClient.GetAsync("api/Tests/EndpointTests2");
        }
        public static global::System.Threading.Tasks.Task<global::System.Net.Http.HttpResponseMessage> EndpointTests2_EndpointTests2_Endpoint2_Endpoint(this global::System.Net.Http.HttpClient httpClient)
        {
            return httpClient.GetAsync("api/Tests/EndpointTests2/Endpoint2");
        }
    }
}