//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dibix.Generators.Tests.Tasks
{
    [global::System.CodeDom.Compiler.GeneratedCode("Dibix.Sdk.Generators", "%GENERATORVERSION%")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public partial class SignDacFileCommand : global::System.CommandLine.Command
    {
        private readonly global::Dibix.Sdk.Abstractions.ILogger _logger;
        private readonly global::System.CommandLine.Argument<string> _inputPropertyFilePathArgument;

        public SignDacFileCommand(global::Dibix.Sdk.Abstractions.ILogger logger) : base("sign", "Appends Dibix metadata to an existing DAC file.")
        {
            _logger = logger;
            _inputPropertyFilePathArgument = new global::System.CommandLine.Argument<string>("inputPropertyFilePath") { Description = "Path to the input property file." };

            Add(_inputPropertyFilePathArgument);

            SetAction(OnExecuteAction);
        }

        public partial global::System.Threading.Tasks.Task<int> Execute(global::Dibix.Generators.Tests.Tasks.SignDacFileCommandInput input);

        private async global::System.Threading.Tasks.Task<int> OnExecuteAction(global::System.CommandLine.ParseResult result, global::System.Threading.CancellationToken cancellationToken)
        {
            string inputPropertyFilePath = result.GetValue(_inputPropertyFilePathArgument);
            global::Dibix.Sdk.Abstractions.InputConfiguration inputConfiguration = global::Dibix.Sdk.Abstractions.InputConfiguration.Parse(inputPropertyFilePath);
            global::Dibix.Generators.Tests.Tasks.SignDacFileCommandInput input = new global::Dibix.Generators.Tests.Tasks.SignDacFileCommandInput
            {
                DacFilePath = inputConfiguration.GetSingleValue<string>("DacFilePath"),
                IsEmbedded = inputConfiguration.GetSingleValue<bool>("IsEmbedded"),
                LockRetryCount = inputConfiguration.GetSingleValue<int>("LockRetryCount")
            };
            int exitCode = await Execute(input).ConfigureAwait(false);
            return exitCode;
        }
    }
}