//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dibix.Generators.Tests.Tasks
{
    public sealed partial class SqlCoreTask : global::Dibix.Sdk.Abstractions.ITask
    {
        [global::System.CodeDom.Compiler.GeneratedCode("Dibix.Generators", "%GENERATORVERSION%")]
        private readonly global::Dibix.Sdk.Abstractions.ILogger _logger;

        [global::System.CodeDom.Compiler.GeneratedCode("Dibix.Generators", "%GENERATORVERSION%")]
        private readonly global::Dibix.Generators.Tests.Tasks.SqlCoreTaskConfiguration _configuration;

        [global::System.CodeDom.Compiler.GeneratedCode("Dibix.Generators", "%GENERATORVERSION%")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public SqlCoreTask(global::Dibix.Sdk.Abstractions.ILogger logger, global::Dibix.Sdk.Abstractions.InputConfiguration configuration)
        {
            this._logger = logger;
            this._configuration = new global::Dibix.Generators.Tests.Tasks.SqlCoreTaskConfiguration
            {
                ProjectName = configuration.GetSingleValue<string>("ProjectName"),
                SqlReferencePath = configuration.GetItems("SqlReferencePath"),
                NamingConventionPrefix = configuration.GetSingleValue<string>("NamingConventionPrefix"),
                Endpoint =
                {
                    EnableExperimentalFeatures = configuration.GetSingleValue<bool>("EnableExperimentalFeatures"),
                    BaseUrl = configuration.GetSingleValue<string>("BaseUrl")
                }
            };
        }

        bool global::Dibix.Sdk.Abstractions.ITask.Execute() => this.Execute();

        private partial bool Execute();
    }
}