//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dibix.Generators.Tests.Tasks
{
    [global::System.CodeDom.Compiler.GeneratedCode("Dibix.Generators", "%GENERATORVERSION%")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public sealed class SqlCoreTaskConfiguration
    {
        public string ProjectName { get; set; }
        public string AreaName { get; set; }
        public global::System.Collections.Generic.ICollection<global::Dibix.Sdk.Abstractions.TaskItem> SqlReferencePath { get; set; }
        public string NamingConventionPrefix { get; set; } = "";
        public global::Dibix.Generators.Tests.Tasks.EndpointConfiguration Endpoint { get; } = new global::Dibix.Generators.Tests.Tasks.EndpointConfiguration();
    }
}