//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dibix.Generators
{
    [global::System.CodeDom.Compiler.GeneratedCode("Dibix.Generators", "%GENERATORVERSION%")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::System.AttributeUsage(global::System.AttributeTargets.Assembly)]
    internal sealed class TestMethodGenerationAttribute : global::System.Attribute
    {
        public global::System.Type BaseType { get; }
        public string Namespace { get; set; }

#pragma warning disable CS8625
#pragma warning disable CS8618
        public TestMethodGenerationAttribute(global::System.Type baseType, string @namespace = null)
#pragma warning restore CS8618
#pragma warning restore CS8625
        {
            this.BaseType = baseType;
        }
    }
}