//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dibix.Generators.Tests.Tasks
{
    public sealed partial class TestConfigurationInherited
    {
        public global::System.Uri PrimitiveClassProperty
        {
            get
            {
                PropertyInitializationTracker.Verify(nameof(PrimitiveClassProperty));
                return _primitiveClassProperty;
            }
            set
            {
                _primitiveClassProperty = value;
                PropertyInitializationTracker.Initialize(nameof(PrimitiveClassProperty));
            }
        }
    }
}