//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dibix.Generators.Tests.Tasks
{
    public abstract partial class TestConfiguration : global::Dibix.Testing.ConfigurationInitializationTracker
    {
        public string? PrimitiveProperty
        {
            get
            {
                PropertyInitializationTracker.Verify(nameof(PrimitiveProperty));
                return _primitiveProperty;
            }
            set
            {
                _primitiveProperty = value;
                PropertyInitializationTracker.Initialize(nameof(PrimitiveProperty));
            }
        }

        public global::Dibix.Generators.Tests.Tasks.TestConfigurationNested Nested => _nested ??= new global::Dibix.Generators.Tests.Tasks.TestConfigurationNested { PropertyInitializationTracker = new global::Dibix.Testing.ConfigurationPropertyInitializationTracker(InitializationToken) };
    }
}