//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dibix.Generators.Tests
{
    internal sealed partial class TestHttpApiDescriptor : global::Dibix.Http.Server.HttpApiDescriptor
    {
        public TestHttpApiDescriptor()
        {
            Metadata.ProductName = "Dibix";
            Metadata.AreaName = "Tests";
        }
        
        public override void Configure(global::Dibix.Http.Server.IHttpApiDiscoveryContext context)
        {
            RegisterController(nameof(global::Dibix.Generators.Tests.Tasks1.EndpointTests1), x =>
            {
                x.AddAction(global::Dibix.Http.Server.LocalReflectionHttpActionTarget.Create(typeof(global::Dibix.Generators.Tests.Tasks1.EndpointTests1), nameof(global::Dibix.Generators.Tests.Tasks1.EndpointTests1.EndpointTests1_Endpoint1_Endpoint)), y =>
                {
                    y.Method = global::Dibix.Http.HttpApiMethod.Get;
                    y.RegisterDelegate((global::Microsoft.AspNetCore.Http.HttpContext httpContext, global::Dibix.Http.Server.AspNetCore.IHttpActionDelegator actionDelegator, global::System.Threading.CancellationToken cancellationToken) => actionDelegator.Delegate(httpContext, new global::System.Collections.Generic.Dictionary<string, object>(), cancellationToken));
                    y.SecuritySchemes.Add("Bearer");
                });
                x.AddAction(global::Dibix.Http.Server.LocalReflectionHttpActionTarget.Create(typeof(global::Dibix.Generators.Tests.Tasks1.EndpointTests1), nameof(global::Dibix.Generators.Tests.Tasks1.EndpointTests1.EndpointTests1_Endpoint2_Endpoint)), y =>
                {
                    y.Method = global::Dibix.Http.HttpApiMethod.Get;
                    y.RegisterDelegate((global::Microsoft.AspNetCore.Http.HttpContext httpContext, global::Dibix.Http.Server.AspNetCore.IHttpActionDelegator actionDelegator, global::System.Threading.CancellationToken cancellationToken) => actionDelegator.Delegate(httpContext, new global::System.Collections.Generic.Dictionary<string, object>(), cancellationToken));
                    y.ChildRoute = "Endpoint2";
                    y.SecuritySchemes.Add("Anonymous");
                });
            });
            RegisterController(nameof(global::Dibix.Generators.Tests.Tasks2.EndpointTests2), x =>
            {
                x.AddAction(global::Dibix.Http.Server.LocalReflectionHttpActionTarget.Create(typeof(global::Dibix.Generators.Tests.Tasks2.EndpointTests2), nameof(global::Dibix.Generators.Tests.Tasks2.EndpointTests2.EndpointTests2_Endpoint1_Endpoint)), y =>
                {
                    y.Method = global::Dibix.Http.HttpApiMethod.Get;
                    y.RegisterDelegate((global::Microsoft.AspNetCore.Http.HttpContext httpContext, global::Dibix.Http.Server.AspNetCore.IHttpActionDelegator actionDelegator, global::System.Threading.CancellationToken cancellationToken) => actionDelegator.Delegate(httpContext, new global::System.Collections.Generic.Dictionary<string, object>(), cancellationToken));
                    y.SecuritySchemes.Add("Bearer");
                });
                x.AddAction(global::Dibix.Http.Server.LocalReflectionHttpActionTarget.Create(typeof(global::Dibix.Generators.Tests.Tasks2.EndpointTests2), nameof(global::Dibix.Generators.Tests.Tasks2.EndpointTests2.EndpointTests2_Endpoint2_Endpoint)), y =>
                {
                    y.Method = global::Dibix.Http.HttpApiMethod.Get;
                    y.RegisterDelegate((global::Microsoft.AspNetCore.Http.HttpContext httpContext, global::Dibix.Http.Server.AspNetCore.IHttpActionDelegator actionDelegator, global::System.Threading.CancellationToken cancellationToken) => actionDelegator.Delegate(httpContext, new global::System.Collections.Generic.Dictionary<string, object>(), cancellationToken));
                    y.ChildRoute = "Endpoint2";
                    y.SecuritySchemes.Add("Bearer");
                    y.AddAuthorizationBehavior(global::Dibix.Http.Server.LocalReflectionHttpActionTarget.Create(typeof(global::Dibix.Generators.Tests.Tasks2.EndpointTests2), nameof(global::Dibix.Generators.Tests.Tasks2.EndpointTests2.EndpointTests2_Endpoint2_Authorization)), _ => { });
                });
            });
        }
    }
}