//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dibix.Generators.Tests.Tasks
{
    public sealed partial class TestConfigurationNested : global::Dibix.Testing.ConfigurationInitializationTracker
    {
        public int? PrimitiveProperty
        {
            get
            {
                PropertyInitializationTracker.Verify(nameof(PrimitiveProperty));
                return _primitiveProperty;
            }
            set
            {
                _primitiveProperty = value;
                PropertyInitializationTracker.Initialize(nameof(PrimitiveProperty));
            }
        }
    }
}