//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dibix.Generators.Tests.Tasks
{
    public abstract partial class TestConfigurationBase : global::Dibix.Testing.ConfigurationInitializationTracker
    {
        public int? PrimitiveTypeProperty
        {
            get
            {
                PropertyInitializationTracker.Verify(nameof(PrimitiveTypeProperty));
                return _primitiveTypeProperty;
            }
            set
            {
                _primitiveTypeProperty = value;
                PropertyInitializationTracker.Initialize(nameof(PrimitiveTypeProperty));
            }
        }

        public global::System.DayOfWeek? EnumProperty
        {
            get
            {
                PropertyInitializationTracker.Verify(nameof(EnumProperty));
                return _enumProperty;
            }
            set
            {
                _enumProperty = value;
                PropertyInitializationTracker.Initialize(nameof(EnumProperty));
            }
        }

        public global::Dibix.Generators.Tests.Tasks.TestConfigurationNested Nested => _nested ??= new global::Dibix.Generators.Tests.Tasks.TestConfigurationNested { PropertyInitializationTracker = new global::Dibix.Testing.ConfigurationPropertyInitializationTracker(InitializationToken) };

        public global::Dibix.Generators.Tests.Tasks.TestConfigurationReusedWithNoValidation Reused => _reused ??= new global::Dibix.Generators.Tests.Tasks.TestConfigurationReusedWithNoValidation();
    }
}