/*------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Dibix SDK 1.0.0.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------*/
using Dibix;

[assembly: ArtifactAssembly]

#region Contracts
namespace Dibix.Sdk.Tests.DomainModel.Features
{
    public enum Feature : short
    {
        Feature1 = 101,
        Feature2 = 102,
        Feature3 = 103,
        Feature4 = 104
    }
}
#endregion