/*------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Dibix SDK 1.0.0.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------*/
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using Dibix;

[assembly: ArtifactAssembly]

#region Accessor
namespace Dibix.Sdk.Tests.Data.Extension.Primitive
{
    [DatabaseAccessor]
    public static class TestAccessor
    {
        // GetSinglePrimitiveResult
        private const string GetSinglePrimitiveResultCommandText = "SELECT NEWID()";

        public static async Task<System.Guid> GetSinglePrimitiveResultAsync(this IDatabaseAccessorFactory databaseAccessorFactory, CancellationToken cancellationToken = default)
        {
            using (IDatabaseAccessor accessor = databaseAccessorFactory.Create())
            {
                return await accessor.QuerySingleAsync<System.Guid>(GetSinglePrimitiveResultCommandText, CommandType.Text, ParametersVisitor.Empty, cancellationToken).ConfigureAwait(false);
            }
        }
    }
}
#endregion