/*------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Dibix SDK 1.0.0.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------*/
using System.Data;
using Dibix;

[assembly: ArtifactAssembly]

#region Accessor
namespace Dibix.Sdk.Tests.Data
{
    [DatabaseAccessor]
    public static class TestAccessor
    {
        // FileResult
        private const string FileResultCommandText = "DECLARE @table TABLE([id] INT NOT NULL, [thumbnail] VARBINARY(MAX) NOT NULL, PRIMARY KEY ([id]))\n\nDECLARE @extension NCHAR(3) = N'png'\n\nDECLARE @fallbackimageid INT = 666\n\nDECLARE @fallbackimagedata VARBINARY(MAX) = 0x1\n\nIF @id = @fallbackimageid\nBEGIN\n    SELECT [type] = CAST(@extension AS NVARCHAR(3))\n         , [data] = CAST(@fallbackimagedata AS VARBINARY(MAX))\nEND\nELSE\nBEGIN\n    SELECT [type] = @extension\n         , [data] = [thumbnail]\n    FROM @table\n    WHERE [id] = @id\nEND";

        public static Dibix.FileEntity FileResult(this IDatabaseAccessorFactory databaseAccessorFactory, int id)
        {
            using (IDatabaseAccessor accessor = databaseAccessorFactory.Create())
            {
                ParametersVisitor @params = accessor.Parameters()
                                                    .SetFromTemplate(new
                                                    {
                                                        id
                                                    })
                                                    .Build();
                return accessor.QuerySingleOrDefault<Dibix.FileEntity>(FileResultCommandText, CommandType.Text, @params);
            }
        }
    }
}
#endregion