/*------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Dibix SDK 1.0.0.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------*/
using System;
using System.Collections.Generic;
using System.Data;
using Dibix;

[assembly: ArtifactAssembly]

#region Accessor
namespace Dibix.Sdk.Tests.Data
{
    [DatabaseAccessor]
    public static class TestAccessor
    {
        // FileResultJsonMergeGridResult
        private const string FileResultJsonMergeGridResultCommandText = "SELECT [x] = N'527B8008-AE6E-421F-91B2-5A0583070BCD', [filename] = N'the_file_result.json'\r\n\r\nSELECT 1";

        public static Dibix.Sdk.Tests.DomainModel.JsonFileResultContract FileResultJsonMergeGridResult(this IDatabaseAccessorFactory databaseAccessorFactory, Action<DatabaseAccessorOptions> configure = null)
        {
            using (IDatabaseAccessor accessor = databaseAccessorFactory.Create("FileResultJsonMergeGridResult", configure))
            {
                using (IMultipleResultReader reader = accessor.QueryMultiple(FileResultJsonMergeGridResultCommandText, CommandType.Text, ParametersVisitor.Empty))
                {
                    Dibix.Sdk.Tests.DomainModel.JsonFileResultContract result = reader.ReadSingleOrDefault<Dibix.Sdk.Tests.DomainModel.JsonFileResultContract>();
                    if (result == null)
                        return null;

                    result.Directions.ReplaceWith(reader.ReadMany<Dibix.Sdk.Tests.DomainModel.Direction>());
                    return result;
                }
            }
        }
    }
}
#endregion

#region Contracts
namespace Dibix.Sdk.Tests.DomainModel
{
    [Flags]
    public enum Direction : int
    {
        Ascending,
        Descending
    }

    public sealed class JsonFileResultContract : IJsonFileMetadata
    {
        public System.Guid? X { get; set; }
        public string FileName { get; set; }
        public IList<Dibix.Sdk.Tests.DomainModel.Direction> Directions { get; private set; }

        public JsonFileResultContract()
        {
            Directions = new List<Dibix.Sdk.Tests.DomainModel.Direction>();
        }
    }
}
#endregion