/*------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Dibix SDK 1.0.0.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------*/
using System;
using System.Collections.Generic;
using System.Data;
using Dibix;

[assembly: ArtifactAssembly]

#region Accessor
namespace Dibix.Sdk.Tests.Data
{
    [DatabaseAccessor]
    public static class TestAccessor
    {
        // FileResultJsonGridResult
        private const string FileResultJsonGridResultCommandText = "SELECT [filename] = N'the_file_result.json'\r\n\r\nSELECT 1";

        public static Dibix.Sdk.Tests.DomainModel.FileResultJsonGridResultResult FileResultJsonGridResult(this IDatabaseAccessorFactory databaseAccessorFactory)
        {
            using (IDatabaseAccessor accessor = databaseAccessorFactory.Create("FileResultJsonGridResult"))
            {
                using (IMultipleResultReader reader = accessor.QueryMultiple(FileResultJsonGridResultCommandText, CommandType.Text, ParametersVisitor.Empty))
                {
                    Dibix.Sdk.Tests.DomainModel.FileResultJsonGridResultResult result = new Dibix.Sdk.Tests.DomainModel.FileResultJsonGridResultResult();
                    result.FileName = reader.ReadSingle<string>();
                    result.Directions.ReplaceWith(reader.ReadMany<Dibix.Sdk.Tests.DomainModel.Direction>());
                    return result;
                }
            }
        }
    }
}
#endregion

#region Contracts
namespace Dibix.Sdk.Tests.DomainModel
{
    [Flags]
    public enum Direction : int
    {
        Ascending,
        Descending
    }

    public sealed class FileResultJsonGridResultResult : IJsonFileMetadata
    {
        public string FileName { get; set; }
        public IList<Dibix.Sdk.Tests.DomainModel.Direction> Directions { get; private set; }

        public FileResultJsonGridResultResult()
        {
            Directions = new List<Dibix.Sdk.Tests.DomainModel.Direction>();
        }
    }
}
#endregion