CREATE PROCEDURE [dbo].[dbx_codeanalysis_error_009]
AS
	--DECLARE @a CHAR
	--DECLARE @b VARCHAR
	DECLARE @c NVARCHAR
	DECLARE @d NCHAR
	DECLARE @e BINARY
	DECLARE @f VARBINARY
	DECLARE @g DECIMAL
	DECLARE @h NUMERIC
	DECLARE @i FLOAT

	--DECLARE @a_ CHAR(1)
	--DECLARE @b_ VARCHAR(1)
	DECLARE @c_ NVARCHAR(1)
	DECLARE @d_ NCHAR(1)
	DECLARE @e_ BINARY(1)
	DECLARE @f_ VARBINARY(1)
	DECLARE @g_ DECIMAL(1)
	DECLARE @h_ NUMERIC(1)
	DECLARE @i_ FLOAT(1)
