namespace Dibix.Sdk.CodeGeneration
{
    public abstract class CodeGenerator
    {
        private readonly IErrorReporter _errorReporter;

        private const string Header = @"/*------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------*/";

        protected CodeGenerator(IErrorReporter errorReporter)
        {
            this._errorReporter = errorReporter;
        }

        public string Generate(CodeGenerationModel model)
        {
            if (this._errorReporter.HasErrors)
                return "\"Please fix the errors first\"";
            
            StringWriter writer = new StringWriter();
            writer.WriteLineRaw(Header);
            this.Write(writer, model);
            return writer.ToString();
        }

        protected abstract void Write(StringWriter writer, CodeGenerationModel model);
    }
}