//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dibix.Sdk.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dibix.Sdk.Tests.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;errors&gt;
        ///  &lt;error
        ///    message=&quot;SRDBX : Dibix : [001] Invalid casing for &apos;SeLeCT&apos; [Select]&quot;
        ///    line=&quot;13&quot;
        ///    column=&quot;2&quot; /&gt;
        ///  &lt;error
        ///    message=&quot;SRDBX : Dibix : [001] Invalid casing for &apos;nvarchar&apos; [Identifier]&quot;
        ///    line=&quot;3&quot;
        ///    column=&quot;13&quot; /&gt;
        ///  &lt;error
        ///    message=&quot;SRDBX : Dibix : [001] Invalid casing for &apos;max&apos; [Identifier]&quot;
        ///    line=&quot;3&quot;
        ///    column=&quot;22&quot; /&gt;
        ///  &lt;error
        ///    message=&quot;SRDBX : Dibix : [001] Invalid casing for &apos;decimal&apos; [Identifier]&quot;
        ///    line=&quot;4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CasingSqlCodeAnalysisRule {
            get {
                return ResourceManager.GetString("CasingSqlCodeAnalysisRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;errors&gt;
        ///  &lt;error
        ///    message=&quot;SRDBX : Dibix : [008] Aliases must be marked with &apos;AS&apos;&quot;
        ///    line=&quot;4&quot;
        ///    column=&quot;25&quot; /&gt;
        ///&lt;/errors&gt;.
        /// </summary>
        internal static string ImplicitAliasSqlCodeAnalysisRule {
            get {
                return ResourceManager.GetString("ImplicitAliasSqlCodeAnalysisRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DISABLED&gt;.
        /// </summary>
        internal static string NoReturnSqlCodeAnalysisRule {
            get {
                return ResourceManager.GetString("NoReturnSqlCodeAnalysisRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        /////     Runtime Version:4.0.30319.42000
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if
        /////     the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////----------------------------------------------------------------------------*/
        ///using System.Collections.Generic;
        ///using System.Collections.ObjectModel;
        ///using System.Reflection;
        ///using D [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ParserTest {
            get {
                return ResourceManager.GetString("ParserTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PrimitiveDataTypeIdentifierSqlCodeAnalysisRule {
            get {
                return ResourceManager.GetString("PrimitiveDataTypeIdentifierSqlCodeAnalysisRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;errors&gt;
        ///  &lt;error
        ///    message=&quot;SRDBX : Dibix : [006] The alias is redundant&quot;
        ///    line=&quot;3&quot;
        ///    column=&quot;17&quot; /&gt;
        ///&lt;/errors&gt;.
        /// </summary>
        internal static string RedundantAliasSqlCodeAnalysisRule {
            get {
                return ResourceManager.GetString("RedundantAliasSqlCodeAnalysisRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;errors&gt;
        ///  &lt;error
        ///    message=&quot;SRDBX : Dibix : [002] Missing schema specification&quot;
        ///    line=&quot;9&quot;
        ///    column=&quot;7&quot; /&gt;
        ///  &lt;error
        ///    message=&quot;SRDBX : Dibix : [002] Missing schema specification&quot;
        ///    line=&quot;17&quot;
        ///    column=&quot;7&quot; /&gt;
        ///  &lt;error
        ///    message=&quot;SRDBX : Dibix : [002] Missing schema specification&quot;
        ///    line=&quot;22&quot;
        ///    column=&quot;14&quot; /&gt;
        ///  &lt;error
        ///    message=&quot;SRDBX : Dibix : [002] Missing schema specification&quot;
        ///    line=&quot;24&quot;
        ///    column=&quot;14&quot; /&gt;
        ///  &lt;error
        ///    messag [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SchemaSqlCodeAnalysisRule {
            get {
                return ResourceManager.GetString("SchemaSqlCodeAnalysisRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        /////     Runtime Version:4.0.30319.42000
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if
        /////     the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////----------------------------------------------------------------------------*/
        ///using System.Reflection;
        ///using Dibix;
        ///
        ///namespace This.Is.A.Custom.Namespace
        ///{
        ///    internal static clas [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SourcesTest {
            get {
                return ResourceManager.GetString("SourcesTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;errors&gt;
        ///  &lt;error
        ///    message=&quot;SRDBX : Dibix : [004] Invalid ascii string literal. Please specify unicode (N&apos;&apos;)&quot;
        ///    line=&quot;3&quot;
        ///    column=&quot;28&quot; /&gt;
        ///&lt;/errors&gt;.
        /// </summary>
        internal static string UnicodeConstantSqlCodeAnalysisRule {
            get {
                return ResourceManager.GetString("UnicodeConstantSqlCodeAnalysisRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;errors&gt;
        ///  &lt;error
        ///    message=&quot;SRDBX : Dibix : [005] Use unicode data types instead of ascii. Please replace VARCHAR with NVARCHAR.&quot;
        ///    line=&quot;1&quot;
        ///    column=&quot;56&quot; /&gt;
        ///  &lt;error
        ///    message=&quot;SRDBX : Dibix : [005] Use unicode data types instead of ascii. Please replace VARCHAR with NVARCHAR.&quot;
        ///    line=&quot;4&quot;
        ///    column=&quot;19&quot; /&gt;
        ///&lt;/errors&gt;.
        /// </summary>
        internal static string UnicodeDataTypeSqlCodeAnalysisRule {
            get {
                return ResourceManager.GetString("UnicodeDataTypeSqlCodeAnalysisRule", resourceCulture);
            }
        }
    }
}
